# Generated by Django 4.1.2 on 2025-11-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lti_user_id', models.CharField(help_text='ID del usuario LTI.', max_length=255)),
                ('lti_context_id', models.CharField(help_text='ID del contexto LTI (curso).', max_length=255)),
                ('interaction_type', models.CharField(help_text="Tipo de interacción (ej. 'viewed', 'completed', 'downloaded').", max_length=50)),
                ('value', models.FloatField(blank=True, help_text='Valor asociado a la interacción (ej. tiempo en segundos, puntuación de un quiz).', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo de la interacción.')),
                ('resource', models.ForeignKey(help_text='Recurso educativo con el que el usuario interactuó.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='resources.educationalresource')),
            ],
            options={
                'verbose_name': 'Interacción de Usuario',
                'verbose_name_plural': 'Interacciones de Usuarios',
                'db_table': 'recommender_app_userinteraction',
            },
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['lti_user_id', 'resource'], name='recommender_lti_use_802255_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['lti_context_id'], name='recommender_lti_con_c19a93_idx'),
        ),
    ]
