# Generated by Django 4.1.2 on 2025-12-04 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='completion_percentage',
            field=models.FloatField(blank=True, help_text='Porcentaje de completitud del recurso (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='downloaded',
            field=models.BooleanField(default=False, help_text='Indica si el usuario descargó el recurso.'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Datos adicionales sobre la interacción (formato JSON).', null=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Valoración del usuario (1-5 estrellas).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='scroll_depth',
            field=models.FloatField(blank=True, help_text='Profundidad de scroll alcanzada (0-100%).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='shared',
            field=models.BooleanField(default=False, help_text='Indica si el usuario compartió el recurso.'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='time_spent',
            field=models.FloatField(blank=True, help_text='Tiempo en segundos que el usuario pasó con el recurso.', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['rating'], name='recommender_rating_ef7196_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['timestamp'], name='recommender_timesta_cae919_idx'),
        ),
    ]
