# Generated by Django 4.2.9 on 2026-04-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_globaluser_ltiidentity_delete_userprofile_and_more'),
        ('interactions', '0002_userinteraction_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='global_user',
            field=models.ForeignKey(blank=True, help_text='Usuario global que realizó la interacción.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='users.globaluser'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='lti_user_id',
            field=models.CharField(blank=True, help_text='ID del usuario LTI (Deprecado a favor de global_user).', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['global_user', 'resource'], name='recommender_global__2dff3c_idx'),
        ),
    ]
