# Generated by Django 5.2.4 on 2025-07-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(help_text='ID único del recurso, puede ser externo si aplica.', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Título del recurso.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Breve descripción del recurso.', null=True)),
                ('url', models.URLField(help_text='URL donde el recurso está disponible.', max_length=500)),
                ('author', models.CharField(blank=True, help_text='Autor o creador del recurso.', max_length=255, null=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('article', 'Artículo'), ('quiz', 'Cuestionario'), ('tool', 'Herramienta Interactiva'), ('other', 'Otro')], default='other', help_text='Tipo de recurso (video, PDF, artículo, etc.).', max_length=50)),
                ('tags', models.CharField(blank=True, help_text="Palabras clave separadas por comas (ej. 'matemáticas, álgebra, ecuaciones').", max_length=500, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], help_text='Nivel de dificultad del recurso.', max_length=50, null=True)),
                ('lti_context_id', models.CharField(blank=True, help_text='ID del contexto LTI (curso) al que pertenece el recurso, si es específico.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurso Educativo',
                'verbose_name_plural': 'Recursos Educativos',
                'unique_together': {('resource_id', 'lti_context_id')},
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lti_user_id', models.CharField(help_text='ID del usuario LTI.', max_length=255)),
                ('lti_context_id', models.CharField(help_text='ID del contexto LTI (curso).', max_length=255)),
                ('interaction_type', models.CharField(help_text="Tipo de interacción (ej. 'viewed', 'completed', 'downloaded').", max_length=50)),
                ('value', models.FloatField(blank=True, help_text='Valor asociado a la interacción (ej. tiempo en segundos, puntuación de un quiz).', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo de la interacción.')),
                ('resource', models.ForeignKey(help_text='Recurso educativo con el que el usuario interactuó.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommender_app.educationalresource')),
            ],
            options={
                'verbose_name': 'Interacción de Usuario',
                'verbose_name_plural': 'Interacciones de Usuarios',
                'indexes': [models.Index(fields=['lti_user_id', 'resource'], name='recommender_lti_use_802255_idx'), models.Index(fields=['lti_context_id'], name='recommender_lti_con_c19a93_idx')],
            },
        ),
    ]
