# Generated by Django 4.2.9 on 2026-03-11 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('svd', 'SVD Matrix Factorization'), ('ncf', 'Neural Collaborative Filtering'), ('sequential', 'Sequential (GRU4Rec)'), ('hybrid', 'Hybrid Content+Collaborative'), ('fm', 'Factorization Machine'), ('ensemble', 'Ensemble')], db_index=True, max_length=50)),
                ('evaluated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('train_loss', models.FloatField(blank=True, null=True)),
                ('train_rmse', models.FloatField(blank=True, help_text='RMSE on training or CV data', null=True)),
                ('test_rmse', models.FloatField(blank=True, help_text='RMSE on held-out test set', null=True)),
                ('test_hit_rate_at_10', models.FloatField(blank=True, null=True)),
                ('precision_at_5', models.FloatField(blank=True, null=True)),
                ('precision_at_10', models.FloatField(blank=True, null=True)),
                ('recall_at_5', models.FloatField(blank=True, null=True)),
                ('recall_at_10', models.FloatField(blank=True, null=True)),
                ('ndcg_at_5', models.FloatField(blank=True, null=True)),
                ('ndcg_at_10', models.FloatField(blank=True, null=True)),
                ('hit_at_5', models.FloatField(blank=True, null=True)),
                ('hit_at_10', models.FloatField(blank=True, null=True)),
                ('mrr', models.FloatField(blank=True, help_text='Mean Reciprocal Rank', null=True)),
                ('map_at_k', models.FloatField(blank=True, help_text='Mean Average Precision@K', null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('coverage', models.FloatField(blank=True, help_text='Catalog coverage (0-1)', null=True)),
                ('n_users', models.IntegerField(blank=True, null=True)),
                ('n_items', models.IntegerField(blank=True, null=True)),
                ('n_interactions', models.IntegerField(blank=True, null=True)),
                ('n_users_evaluated', models.IntegerField(blank=True, null=True)),
                ('ensemble_weight', models.FloatField(blank=True, help_text='Weight assigned in ensemble', null=True)),
                ('raw_metrics', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['model_name', '-evaluated_at'], name='analytics_m_model_n_0b0809_idx')],
            },
        ),
    ]
