# Generated by Django 4.2.9 on 2026-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.CharField(help_text='ID único del contexto LTI.', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Nombre del curso o contexto.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contexto LTI',
                'verbose_name_plural': 'Contextos LTI',
            },
        ),
    ]
