"""
Django settings for lti_recommender_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

XAPI_BEARER_TOKEN = 'lti_recommender_xapi_secret_2026'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jg)6h)8!+iv14os2zi76$_5ao-^h99zic!il%-ek2y9jli2*ue'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'pylti1p3.contrib.django.lti1p3_tool_config',
    'django_celery_beat',  # Celery Beat scheduler
    
    # Project apps
    'lti_recommender_project.apps.resources',
    'lti_recommender_project.apps.interactions',
    'lti_recommender_project.apps.lti_integration',
    'lti_recommender_project.apps.users',
    'lti_recommender_project.apps.recommendations',
    'lti_recommender_project.apps.analytics',
]

# ... (otras configuraciones)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Configuración para cookies SameSite en desarrollo local (NO PARA PRODUCCIÓN)
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False # <--- ¡CUIDADO! Esto desactiva la seguridad de la cookie
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_SECURE = False # <--- ¡CUIDADO! Esto desactiva la seguridad de la cookie
CSRF_TRUSTED_ORIGINS = [
    'chrome-extension://ichljheklenhagioklbflojlebie',
    'http://localhost:8080',
    'http://localhost',
    'http://127.0.0.1',
]

# Asegúrate de que el middleware XFrameOptionsMiddleware esté comentado (como ya lo tienes)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lti_recommender_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
LTI_TOOL_CONFIG = {
    'CLIENT_ID': 'IYJra9nMaKaT6Lx', # Este lo obtendrás de Moodle
    'JWKS_URL': 'http://127.0.0.1:8000/lti/jwks/', # URL de tus claves públicas
    'AUTH_LOGIN_URL': 'http://127.0.0.1:8000/lti/login/', # Endpoint de inicio de sesión OIDC
    'LAUNCH_URL': 'http://127.0.0.1:8000/lti/launch/', # Endpoint de lanzamiento LTI
    'TOOL_NAME': 'Sistema de Recomendación EPAI',
    'TOOL_DESCRIPTION': 'Un sistema de recomendación de temas de interés para Moodle integrado con LTI.',
    # ¡ACTUALIZA ESTAS RUTAS!
    'PUBLIC_KEY_FILE': str(BASE_DIR / 'lti_public_key.pem'),
    'PRIVATE_KEY_FILE': str(BASE_DIR / 'lti_private_key.pem'),
    # Configuración para servicios LTI Advantage (NRPS, AGS, Deep Linking)
    'ENABLE_NRPS': True,
    'ENABLE_AGS': False, # Si no vas a enviar calificaciones, puedes deshabilitarlo
    'ENABLE_DEEP_LINKING': True,
    # URLs de Moodle (Platform)
    'MOODLE_AUTH_URL': 'http://localhost/stable_main/mod/lti/auth.php', # Ej: https://your-moodle.com/mod/lti/auth.php
    'MOODLE_TOKEN_URL': 'http://localhost/stable_main/mod/lti/token.php', # Ej: https://your-moodle.com/mod/lti/token.php
    'MOODLE_JWKS_URL': 'http://localhost/stable_main/mod/lti/certs.php', # Ej: https://your-moodle.com/mod/lti/certs.php
}

WSGI_APPLICATION = 'lti_recommender_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Recommendation Engine Settings
RECOMMENDATION_CONFIG = {
    # Multilingual model — supports Spanish + English (768 dims)
    'EMBEDDING_MODEL': 'paraphrase-multilingual-mpnet-base-v2',
    'EMBEDDING_DIMENSION': 768,
    'SIMILARITY_THRESHOLD': 0.3,
    'CONTENT_WEIGHT': 0.5,
    'USER_WEIGHT': 0.3,
    'POPULARITY_WEIGHT': 0.2,
    'RECOMMENDATION_CACHE_TTL': 1800,
    'ACTIVE_USER_DAYS': 7,
}

EMBEDDING_MODEL = RECOMMENDATION_CONFIG['EMBEDDING_MODEL']

# Celery Settings (using Redis as requested for event pipeline)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_TASK_ALWAYS_EAGER = False  # Set to False to run asynchronously via worker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}