# Generated by Django 4.1.2 on 2025-12-04 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('lti_user_id', models.CharField(help_text='ID único del usuario LTI.', max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, help_text='Nombre del usuario.', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email del usuario.', max_length=254, null=True)),
                ('inferred_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', help_text='Nivel inferido del usuario basado en sus interacciones.', max_length=50)),
                ('preferred_resource_types', models.JSONField(blank=True, default=dict, help_text="Tipos de recursos preferidos y su frecuencia de interacción (ej. {'video': 10, 'pdf': 5}).")),
                ('interest_tags', models.TextField(blank=True, help_text='Tags de interés del usuario, separados por comas.', null=True)),
                ('total_interactions', models.IntegerField(default=0, help_text='Número total de interacciones del usuario.', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_completion', models.FloatField(default=0.0, help_text='Promedio de porcentaje de completitud de los recursos interactuados.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_rating', models.FloatField(blank=True, help_text='Promedio de ratings dados por el usuario.', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('first_interaction', models.DateTimeField(auto_now_add=True, help_text='Fecha de primera interacción del usuario.')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Última actividad del usuario.')),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales del perfil (formato JSON).', null=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'recommender_app_userprofile',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['inferred_level'], name='recommender_inferre_bb210a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['last_active'], name='recommender_last_ac_43497d_idx'),
        ),
    ]
