# Generated by Django 4.2.9 on 2026-03-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_integration', '0002_lticontext'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contexts',
            field=models.ManyToManyField(blank=True, help_text='Cursos en los que el usuario ha interactuado.', related_name='users', to='lti_integration.lticontext'),
        ),
    ]
