# Generated by Django 4.2.9 on 2026-04-29 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lti_integration', '0002_lticontext'),
        ('users', '0002_userprofile_contexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID global único del usuario.', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Email principal del usuario (opcional).', max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, help_text='Nombre global del usuario.', max_length=255, null=True)),
                ('inferred_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', help_text='Nivel inferido global.', max_length=50)),
                ('preferences_json', models.JSONField(blank=True, default=dict, help_text="Preferencias de tipos de recursos (ej. {'video': 10, 'pdf': 5}).")),
                ('interest_tags', models.TextField(blank=True, help_text='Tags de interés globales, separados por comas.', null=True)),
                ('total_interactions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_completion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('first_interaction', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario Global',
                'verbose_name_plural': 'Usuarios Globales',
                'db_table': 'recommender_app_globaluser',
            },
        ),
        migrations.CreateModel(
            name='LTIIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.URLField(help_text='El emisor del token LTI (ej. https://moodle.example.com).', max_length=255)),
                ('sub', models.CharField(help_text='El identificador de usuario (subject) dentro de este emisor.', max_length=255)),
                ('platform_id', models.CharField(blank=True, help_text='Tool Consumer Instance GUID.', max_length=255, null=True)),
                ('role', models.CharField(blank=True, help_text='Rol del usuario en la plataforma (ej. Learner, Instructor).', max_length=100, null=True)),
                ('contexts', models.ManyToManyField(blank=True, help_text='Cursos en los que esta identidad ha interactuado.', related_name='identities', to='lti_integration.lticontext')),
                ('global_user', models.ForeignKey(help_text='Usuario global asociado a esta identidad LTI.', on_delete=django.db.models.deletion.CASCADE, related_name='lti_identities', to='users.globaluser')),
            ],
            options={
                'verbose_name': 'Identidad LTI',
                'verbose_name_plural': 'Identidades LTI',
                'db_table': 'recommender_app_ltiidentity',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['inferred_level'], name='recommender_inferre_41a087_idx'),
        ),
        migrations.AddIndex(
            model_name='globaluser',
            index=models.Index(fields=['last_active'], name='recommender_last_ac_586b25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ltiidentity',
            unique_together={('issuer', 'sub')},
        ),
    ]
