# Generated by Django 4.1.2 on 2025-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(help_text='ID único del recurso, puede ser externo si aplica.', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Título del recurso.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Breve descripción del recurso.', null=True)),
                ('url', models.URLField(help_text='URL donde el recurso está disponible.', max_length=500)),
                ('author', models.CharField(blank=True, help_text='Autor o creador del recurso.', max_length=255, null=True)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('article', 'Artículo'), ('quiz', 'Cuestionario'), ('tool', 'Herramienta Interactiva'), ('other', 'Otro')], default='other', help_text='Tipo de recurso (video, PDF, artículo, etc.).', max_length=50)),
                ('tags', models.CharField(blank=True, help_text="Palabras clave separadas por comas (ej. 'matemáticas, álgebra, ecuaciones').", max_length=500, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], help_text='Nivel de dificultad del recurso.', max_length=50, null=True)),
                ('lti_context_id', models.CharField(blank=True, help_text='ID del contexto LTI (curso) al que pertenece el recurso, si es específico.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurso Educativo',
                'verbose_name_plural': 'Recursos Educativos',
                'db_table': 'recommender_app_educationalresource',
                'unique_together': {('resource_id', 'lti_context_id')},
            },
        ),
    ]
