# Generated by Django 4.1.2 on 2025-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector de embedding semántico del recurso (formato JSON array).', null=True),
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text="Versión del modelo de embedding usado (ej. 'all-MiniLM-L6-v2').", max_length=100, null=True),
        ),
    ]
