# Generated by Django 4.2.9 on 2026-01-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_educationalresource_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalresource',
            name='url',
            field=models.TextField(help_text='URL donde el recurso está disponible.'),
        ),
    ]
