# Generated by Django 4.2.9 on 2026-03-11 02:10

from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_educationalresource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se actualizó el embedding.', null=True),
        ),
        migrations.RemoveField(
            model_name='educationalresource',
            name='embedding',
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector de embedding semántico (pgvector, 768 dims).', null=True),
        ),
        migrations.AlterField(
            model_name='educationalresource',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text="Versión del modelo de embedding (ej. 'paraphrase-multilingual-mpnet-base-v2').", max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='educationalresource',
            index=models.Index(fields=['resource_type'], name='recommender_resourc_d02e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalresource',
            index=models.Index(fields=['difficulty_level'], name='recommender_difficu_4c680f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalresource',
            index=models.Index(fields=['lti_context_id'], name='recommender_lti_con_154583_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalresource',
            index=models.Index(fields=['embedding_updated_at'], name='recommender_embeddi_f25212_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalresource',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='resource_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
